services:
    db:
      ports:
        - 5431:5432
      container_name: postgresql_container
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=karthikr1234
        - POSTGRES_USER=karthik
      volumes:
        - /home/karthik/Desktop/postgres_db:/var/lib/postgresql/data
      restart: always
    backend:
      build: .
      container_name: website_container
      ports:
        - :8080
      environment:
        db-url: jdbc:postgresql://localhost:5432/postgres
        db-username: karthik
        db-password: karthikr1234
      depends_on:
        - db
      restart: always